spring.datasource.url=jdbc:postgresql://dpg-d7g6okt8nd3s73a7fk1g-a.oregon-postgres.render.com:5432/uniportal_grc1
spring.datasource.username=uniportal_grc1_user
spring.datasource.password=evw6Kng9b2WudTCdvIfNQHEu1RY02C81

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



